### ISSUE TITLE
fix minor content issues on landing page

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#19]
**Replace** A small step can have an immediate impact, **or** make a significant difference in your life with A small step can have an immediate impact, **and** make a significant difference in your life

**Replace** Receive a daily challenge on you your with Receive a daily challenge on your

**Remove** links on the outcomes section

**fix** footer links

**Comment by fakruddin11984** [comment]
Remove links on the outcomes section and border alignment- Done

fix footer links- Done
