### ISSUE TITLE
Home Page Menu bar

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#22]
We need to add menu bar items to the home page.

I propose we have:
How it works - anchor link to How it works section
Testimonials - anchor link to What people are saying section
Sign up - opens sign up modal
Sign in - opens sign in modal

For mobile, we will need a solution for mobile. Hamburger menu?

**Comment by kushal-likhi** [comment]
@fakruddin11984 Can you get this updated. Signup and Signins are buttons opening up the modals, and rest 2 are # links taking to respective sections of the page.

**Comment by javierorange** [comment]
@fakruddin11984 on mobile hamburger menu, when you click a menu item, menu should close. Could you fix it?

cc @kushal-likhi 
![image uploaded from ios 24](https://user-images.githubusercontent.com/14277031/37905112-badbebb8-30f5-11e8-9813-fead79dc2efd.jpg)

**Comment by javierorange** [comment]
I checked and the issue is fixed. Great job @fakruddin11984
