### ISSUE TITLE
on email templates, replace Postmaster (from) with The Active Pathways Team

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#43]
currently emails are received from Postmaster (postmaster@mg.smartplayds.com).
Change Postmaster to The Active Pathways Team

**Comment by kushal-likhi** [comment]
in mail sending from use the From email address as `The Active Pathways Team <postmaster@mg.smartplayds.com>` instead of plain `postmaster@mg.smartplayds.com` . @iamsonumalik

**Comment by javierorange** [comment]
QA done.
