### ISSUE TITLE
Fix welcome email

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#46]
Fix welcome email copy:
- In the sentence **You’ve made first move** your is missing. It should be like this:
**You’ve made your first move**

- correct the typo:
to exercise in your daily **routing**. should be **routine**

- Add link to **our wellbeing programme** (https://www.surveymonkey.co.uk/r/P6MLZZK)

- Add link to **our Facebook page** (https://www.facebook.com/getwalkers/)

- Remove the **Get Started** button

**Comment by kushal-likhi** [comment]
@javierorange should we validate/confirm email on clicking `get Started` ?

**Comment by javierorange** [comment]
@kushal-likhi That's a good point. In this case we will need to alter the copy.
We can add
"By clicking on the following link, you are confirming your email"
and the button should be {confirm email address}

**Comment by javierorange** [comment]
Make the font darker (5F5F5F)
add underline to links

**Comment by javierorange** [comment]
@fakruddin11984 @kushal-likhi
Incorrect url link. Remove the ")"   There is a ")" on the facebook url https://www.facebook.com/getwalkers/)

**Comment by kushal-likhi** [comment]
@javierorange  Updated, please check.
