### ISSUE TITLE
Add end of the programme email template

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#48]
- Add job to trigger end of the programme email (9:00 AM UTC Day 7 + 1 day)
- Use same email template as welcome email
- use the following copy

Hi [firstname],

We hope you enjoyed our Starter Programme. 

Our aim was to help you be more aware of your choices and help you identify new opportunities to be more active on your daily life. 

Our mission is to help as many people to be more active, healthier and happier.

As you, we are at the beginning of our Journey and we need your help to know if we are on the right track.

Today's challenge is to complete our short survey (< 1 minute) :-)

{Give feedback button} (use link https://www.surveymonkey.co.uk/r/P5SZ7PQ)

**Comment by kushal-likhi** [comment]
@fakruddin11984 Create the email template with "copy" changes. 

@iamsonumalik integrate it with a new job.
