### ISSUE TITLE
Provide image dimensions and aspect ratios

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#89]
programme thumbnail image aspect ratio - 7 : 4
 programme thumbnail image dimensions - 350 : 200

programme large Image dimensions - 1446 : 450

programme large Image  aspect ratio- 7 : 2

**Comment by meghna1711** [comment]
Add two fields for images under Programme section in admin panel named Thumbnail Image and  Image. Thumbnail image will be shown on the programme tile and another one will be shown in programme detail background.
