### ISSUE TITLE
Home Page Tweaks

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#9]
- add logo

- remove "inverse" button

- change Outcome subtitle font colour to navy and use bold font.

- align last testimonials

- remove Read more from testimonials section

- add Footer copy

- change footer background colour to navy solid

left: 
Reach us (bold) activepathways@smartplayds.com

Join our community on Facebook (bold) [https://www.facebook.com/getwalkers/]

right:
Active Pathways is an initiative of:

SMARTplayds Limited
Collaborate Works - Steward House 14 Commercial Way 
Woking GU21 6ET
+44 - 203 695 2189
Registered in England and Wales 9462175

**Comment by javierorange** [comment]
@fakruddin11984 could you replace the logo with the correct one? The correct one has rounded points (see image)

Logo files are located here https://drive.google.com/drive/u/1/folders/1oTU12bgKTKdd2BEV1qmp0gLxG3SbBe5R


![social media profile pic_logo](https://user-images.githubusercontent.com/14277031/36694825-6cf79236-1b37-11e8-894e-6ecdce9416b1.png)

**Comment by javierorange** [comment]
@kushal-likhi @fakruddin11984 

_**This is the current status of this issue, could you please check it?**_

add logo - The anagram has been added, could you add the text "Active Pathways"?

remove "inverse" button - DONE

change Outcome(Feel more confident, increase your wellbeing, change your life) **subtitles** font colour to navy and use bold font. - PENDING

align last testimonials - DONE

remove Read more from testimonials section - DONE

add Footer copy - PENDING

change footer background colour to navy solid - PENDING

The subtitles text is PENDING (there's a pending pull request) and I changed the How it works copy (in the same pull request)
https://github.com/javierorange/activepathways/pull/10

There is a typo on the "Join now for free" section speacial (should be **special**)

**Comment by kushal-likhi** [comment]
@fakruddin11984 Can you look in the issues.

**Comment by fakruddin11984** [comment]
1. "Active Pathways" text add logo.
2. Fixed Outcome subtitle font color and font weight bold.
3. Fixed footer background color.
4. Fixed how it work section ui issues

**Comment by javierorange** [comment]
@fakruddin11984 could you please add the footer copy?

left side of the footer:

**Reach us** (mailto: activepathways@smartplayds.com)
**Join our community on Facebook** (link) [https://www.facebook.com/getwalkers/]

right side of the footer

Active Pathways is an initiative of:
SMARTplayds Limited
Collaborate Works - Steward House 14 Commercial Way
Woking GU21 6ET
+44 - 203 695 2189
Registered in England and Wales 9462175
