### ISSUE TITLE
fix minor content issues on home page

### ISSUE THREAD

**Issue by javierorange** [javierorange/activepathways#93]
in all pages:
Replace *program* or *programs* with *programme* and *programmes* (the word programme is used in UK instead of program)

Coming soon programme tile:
- Replace content
*Program title
If it fits, i sits burrow under covers. Destroy couch leave hair everywhere, *

with: Otago Strength and Balance Programme (as program title)
Description: Improve your balance and strength, general fitness and well-being. 
-  Add active Surrey partner strip
- Remove link to CTA "coming soon"

Become a partner tile:
- replace current content with
Title: Your programme here
Description: Partner with us to deliver your physical activity programme

Become a partner section
- Amend the typo. Replace *parter* with *partner*

**Comment by meghna1711** [comment]
Remove the offered_image field from programmes and instead show just the offered_text on programme cards
